#!/bin/bash

# This project is licensed under the MIT License (see LICENSE).

set -eo pipefail

s="$(passless list | rofi -dmenu -p 'passless')"
[[ -z "$s" ]] && exit 1
passless -c -l "${s##*| }" "${s%% |*}" > /dev/null
