#!/bin/bash

# This project is licensed under the MIT License (see LICENSE).

set -eo pipefail

sites="$(passless list)" || exit $?
s="$(echo "$sites" | rofi -dmenu -p 'passless')"
[[ -z "$s" ]] && exit 1
passless -c -l "${s##*| }" "${s%% |*}" > /dev/null
